import 'package:flutter/material.dart';

enum TreatmentId {
  oxygen,
  airwayPositioning,
  suction,
  bvm,
  recoveryPosition,
  positionOfComfort,
  bleedingControl,
  tourniquet,
  woundDressing,
  splinting,
  spinalMotionRestriction,
  burns,
  shockManagement,
  rapidTransport,
  requestAls,
  reassessment,
  oralGlucose,
  aspirin,
  nitroglycerinAssist,
  epinephrineAutoInjector,
  albuterolAssist,
  naloxone,
  activatedCharcoal,
}

extension TreatmentIdX on TreatmentId {
  String get id => name;

  String get title => switch (this) {
    TreatmentId.oxygen => 'Oxygen',
    TreatmentId.airwayPositioning => 'Airway Positioning',
    TreatmentId.suction => 'Suction',
    TreatmentId.bvm => 'BVM Ventilation',
    TreatmentId.recoveryPosition => 'Recovery Position',
    TreatmentId.positionOfComfort => 'Position of Comfort',
    TreatmentId.bleedingControl => 'Bleeding Control',
    TreatmentId.tourniquet => 'Tourniquet',
    TreatmentId.woundDressing => 'Wound Dressing',
    TreatmentId.splinting => 'Splinting',
    TreatmentId.spinalMotionRestriction => 'Spinal Motion Restriction',
    TreatmentId.burns => 'Burn Cooling & Covering',
    TreatmentId.shockManagement => 'Shock Management',
    TreatmentId.rapidTransport => 'Rapid Transport',
    TreatmentId.requestAls => 'Request ALS',
    TreatmentId.reassessment => 'Reassessment',
    TreatmentId.oralGlucose => 'Oral Glucose',
    TreatmentId.aspirin => 'Aspirin',
    TreatmentId.nitroglycerinAssist => 'Nitroglycerin Assist',
    TreatmentId.epinephrineAutoInjector => 'Epinephrine Auto-Injector',
    TreatmentId.albuterolAssist => 'Albuterol Assist',
    TreatmentId.naloxone => 'Naloxone',
    TreatmentId.activatedCharcoal => 'Activated Charcoal',
  };

  bool get isMedication => switch (this) {
    TreatmentId.oralGlucose || TreatmentId.aspirin || TreatmentId.nitroglycerinAssist || TreatmentId.epinephrineAutoInjector || TreatmentId.albuterolAssist || TreatmentId.naloxone || TreatmentId.activatedCharcoal => true,
    _ => false,
  };

  IconData get icon => switch (this) {
    TreatmentId.oxygen => Icons.air,
    TreatmentId.airwayPositioning => Icons.accessibility_new,
    TreatmentId.suction => Icons.cleaning_services,
    TreatmentId.bvm => Icons.masks,
    TreatmentId.recoveryPosition => Icons.hotel,
    TreatmentId.positionOfComfort => Icons.event_seat,
    TreatmentId.bleedingControl => Icons.bloodtype,
    TreatmentId.tourniquet => Icons.emergency,
    TreatmentId.woundDressing => Icons.healing,
    TreatmentId.splinting => Icons.back_hand,
    TreatmentId.spinalMotionRestriction => Icons.straighten,
    TreatmentId.burns => Icons.local_fire_department,
    TreatmentId.shockManagement => Icons.thermostat,
    TreatmentId.rapidTransport => Icons.local_shipping,
    TreatmentId.requestAls => Icons.support_agent,
    TreatmentId.reassessment => Icons.repeat,
    TreatmentId.oralGlucose => Icons.cookie,
    TreatmentId.aspirin => Icons.medication,
    TreatmentId.nitroglycerinAssist => Icons.favorite,
    TreatmentId.epinephrineAutoInjector => Icons.flash_on,
    TreatmentId.albuterolAssist => Icons.airline_seat_flat,
    TreatmentId.naloxone => Icons.health_and_safety,
    TreatmentId.activatedCharcoal => Icons.science,
  };
}

@immutable
class TreatmentLesson {
  const TreatmentLesson({
    required this.id,
    required this.usedFor,
    required this.whenToConsider,
    required this.supportingFindings,
    required this.checkFirst,
    required this.redFlags,
    required this.reassess,
    required this.commonMistake,
    required this.practicePrompt,
    required this.practiceOptions,
    required this.correctOptionIndex,
    required this.practiceFeedback,
  });

  final TreatmentId id;
  final String usedFor;
  final String whenToConsider;
  final List<String> supportingFindings;
  final List<String> checkFirst;
  final List<String> redFlags;
  final List<String> reassess;
  final String commonMistake;
  final String practicePrompt;
  final List<String> practiceOptions;
  final int correctOptionIndex;
  final String practiceFeedback;
}

class TreatmentContent {
  static TreatmentLesson? lessonFor(String id) {
    final t = TreatmentId.values.cast<TreatmentId?>().firstWhere((x) => x?.id == id, orElse: () => null);
    if (t == null) return null;
    return lessons[t];
  }

  static const List<TreatmentId> treatments = [
    TreatmentId.oxygen,
    TreatmentId.airwayPositioning,
    TreatmentId.suction,
    TreatmentId.bvm,
    TreatmentId.recoveryPosition,
    TreatmentId.positionOfComfort,
    TreatmentId.bleedingControl,
    TreatmentId.tourniquet,
    TreatmentId.woundDressing,
    TreatmentId.splinting,
    TreatmentId.spinalMotionRestriction,
    TreatmentId.burns,
    TreatmentId.shockManagement,
    TreatmentId.rapidTransport,
    TreatmentId.requestAls,
    TreatmentId.reassessment,
  ];

  static const List<TreatmentId> medications = [
    TreatmentId.oralGlucose,
    TreatmentId.aspirin,
    TreatmentId.nitroglycerinAssist,
    TreatmentId.epinephrineAutoInjector,
    TreatmentId.albuterolAssist,
    TreatmentId.naloxone,
    TreatmentId.activatedCharcoal,
  ];

  static const Map<TreatmentId, TreatmentLesson> lessons = {
    TreatmentId.oxygen: TreatmentLesson(
      id: TreatmentId.oxygen,
      usedFor: 'Respiratory distress, hypoxia, shock, or other protocol-approved oxygen needs.',
      whenToConsider: 'When breathing, oxygenation, perfusion, or patient condition suggests oxygen may help.',
      supportingFindings: ['SpO₂ low or trending down', 'Increased work of breathing', 'Cyanosis', 'Shock signs', 'Altered mental status with breathing concern'],
      checkFirst: ['Airway is open', 'Patient can tolerate the device', 'Correct delivery device per protocol', 'Need for BVM instead of simple oxygen'],
      redFlags: ['Inadequate breathing needs ventilation support, not just oxygen', 'Do not treat the pulse ox number alone'],
      reassess: ['Work of breathing', 'SpO₂ trend', 'Mental status', 'Breath sounds if available'],
      commonMistake: 'Putting oxygen on but missing that the patient needs BVM assistance.',
      practicePrompt: 'Patient is short of breath, speaking in 2-word phrases, SpO₂ 88% on room air. What should be considered?',
      practiceOptions: ['Oxygen and airway/breathing reassessment', 'No treatment because patient is awake', 'Only SAMPLE questions'],
      correctOptionIndex: 0,
      practiceFeedback: 'Oxygen may be indicated, but you must also reassess whether breathing is adequate.',
    ),
    TreatmentId.airwayPositioning: TreatmentLesson(
      id: TreatmentId.airwayPositioning,
      usedFor: 'Opening or maintaining a patient airway.',
      whenToConsider: 'Any time airway patency is questionable or mental status is decreased.',
      supportingFindings: ['Snoring respirations', 'Decreased LOC', 'Vomiting risk', 'Unable to maintain own airway'],
      checkFirst: ['Trauma concern', 'Need for jaw thrust vs head tilt/chin lift', 'Need for suction', 'Need for airway adjunct per protocol'],
      redFlags: ['Do not ignore noisy breathing', 'Use spinal precautions when indicated'],
      reassess: ['Airway sounds', 'Chest rise', 'Mental status', 'Oxygenation'],
      commonMistake: 'Starting history questions before fixing airway positioning.',
      practicePrompt: 'Unresponsive patient has snoring respirations. First airway action?',
      practiceOptions: ['Reposition/open airway', 'Ask OPQRST', 'Give aspirin'],
      correctOptionIndex: 0,
      practiceFeedback: 'Snoring respirations suggest airway obstruction by the tongue; open the airway first.',
    ),
    TreatmentId.suction: TreatmentLesson(
      id: TreatmentId.suction,
      usedFor: 'Clearing fluid, blood, vomit, or secretions from the airway.',
      whenToConsider: 'When airway contamination is present or sounds wet/gurgling.',
      supportingFindings: ['Gurgling respirations', 'Vomiting', 'Blood or secretions in mouth', 'Poor airway control'],
      checkFirst: ['Suction unit ready', 'Appropriate catheter', 'Limit suction time per training/protocol', 'Airway positioning'],
      redFlags: ['Do not delay suction when airway is contaminated', 'Monitor for worsening hypoxia'],
      reassess: ['Airway patency', 'Breathing', 'SpO₂', 'Need for BVM'],
      commonMistake: 'Trying to ventilate through vomit or secretions.',
      practicePrompt: 'Patient has gurgling respirations and vomit in the mouth. Best first action?',
      practiceOptions: ['Suction the airway', 'Apply a splint', 'Ask last oral intake first'],
      correctOptionIndex: 0,
      practiceFeedback: 'Clear the airway before moving on to other assessment steps.',
    ),
    TreatmentId.bvm: TreatmentLesson(
      id: TreatmentId.bvm,
      usedFor: 'Assisting or providing ventilations when breathing is inadequate.',
      whenToConsider: 'Slow, shallow, absent, or ineffective respirations.',
      supportingFindings: ['RR too slow or too fast with fatigue', 'Poor chest rise', 'Cyanosis', 'Altered mental status', 'Respiratory failure'],
      checkFirst: ['Airway position', 'Mask seal', 'Oxygen attached if available', 'Need for two-person BVM'],
      redFlags: ['Oxygen alone does not fix inadequate ventilation', 'Avoid over-ventilation'],
      reassess: ['Chest rise', 'Rate', 'SpO₂', 'Mental status', 'Pulse'],
      commonMistake: 'Giving oxygen by mask when the patient cannot ventilate effectively.',
      practicePrompt: 'Patient has RR 6/min, shallow breathing, cyanotic lips. Best treatment?',
      practiceOptions: ['BVM ventilations', 'Position of comfort only', 'Aspirin'],
      correctOptionIndex: 0,
      practiceFeedback: 'Inadequate breathing needs assisted ventilations.',
    ),
    TreatmentId.recoveryPosition: TreatmentLesson(
      id: TreatmentId.recoveryPosition,
      usedFor: 'Protecting the airway in a breathing patient with decreased responsiveness.',
      whenToConsider: 'Breathing is adequate but patient may vomit or cannot fully protect airway.',
      supportingFindings: ['Decreased LOC', 'No trauma concern', 'Vomiting risk', 'Adequate breathing'],
      checkFirst: ['Trauma/spinal concern', 'Airway and breathing remain adequate', 'Can safely position patient'],
      redFlags: ['Do not place in recovery position if spinal precautions are required unless protocol allows/needed for airway'],
      reassess: ['Airway', 'Breathing', 'Pulse', 'Mental status'],
      commonMistake: 'Leaving a vomiting altered patient flat on their back.',
      practicePrompt: 'Patient is breathing adequately but drowsy and nauseated with no trauma concern. Best position?',
      practiceOptions: ['Recovery position', 'Supine flat only', 'Tourniquet'],
      correctOptionIndex: 0,
      practiceFeedback: 'Recovery position helps protect the airway when appropriate.',
    ),
    TreatmentId.positionOfComfort: TreatmentLesson(
      id: TreatmentId.positionOfComfort,
      usedFor: 'Reducing distress while supporting breathing, pain, or comfort.',
      whenToConsider: 'Stable patient with breathing difficulty, chest pain, abdominal pain, or general discomfort.',
      supportingFindings: ['Awake and able to maintain airway', 'Shortness of breath', 'Chest discomfort', 'Pain'],
      checkFirst: ['No immediate life threat needing another position', 'Blood pressure/perfusion', 'Spinal precautions if needed'],
      redFlags: ['Do not force a position that worsens breathing or perfusion'],
      reassess: ['Breathing effort', 'Pain', 'Skin signs', 'Vitals'],
      commonMistake: 'Laying every patient flat even when sitting upright improves breathing.',
      practicePrompt: 'Awake SOB patient is most comfortable sitting upright. What position is reasonable?',
      practiceOptions: ['Position of comfort', 'Force supine flat', 'Trendelenburg only'],
      correctOptionIndex: 0,
      practiceFeedback: 'For many breathing patients, sitting upright may reduce work of breathing.',
    ),
    TreatmentId.bleedingControl: TreatmentLesson(
      id: TreatmentId.bleedingControl,
      usedFor: 'Stopping external bleeding and preventing shock.',
      whenToConsider: 'Any significant external bleeding.',
      supportingFindings: ['Active bleeding', 'Blood-soaked clothing', 'Pale/cool/clammy', 'Tachycardia'],
      checkFirst: ['Expose wound safely', 'Direct pressure', 'Need for tourniquet', 'PPE/BSI'],
      redFlags: ['Uncontrolled major bleeding is a life threat', 'Do not delay for detailed history'],
      reassess: ['Bleeding control', 'Pulse distal to injury if appropriate', 'Skin signs', 'Mental status'],
      commonMistake: 'Doing vitals before controlling obvious major bleeding.',
      practicePrompt: 'Patient has heavy bleeding from forearm laceration. First treatment priority?',
      practiceOptions: ['Control bleeding', 'Ask SAMPLE first', 'Check pupils first'],
      correctOptionIndex: 0,
      practiceFeedback: 'Major external bleeding is a circulation life threat.',
    ),
    TreatmentId.tourniquet: TreatmentLesson(
      id: TreatmentId.tourniquet,
      usedFor: 'Controlling severe extremity bleeding when direct pressure is not enough or bleeding is life-threatening.',
      whenToConsider: 'Severe extremity hemorrhage or uncontrolled bleeding.',
      supportingFindings: ['Pulsatile bleeding', 'Pooling blood', 'Amputation/near amputation', 'Direct pressure ineffective'],
      checkFirst: ['Extremity wound', 'Placement per training', 'Time applied', 'Local protocol'],
      redFlags: ['Do not loosen once applied unless protocol directs', 'Document time'],
      reassess: ['Bleeding stopped', 'Distal pulse if appropriate', 'Pain', 'Shock signs'],
      commonMistake: 'Waiting too long to apply a tourniquet for life-threatening extremity bleeding.',
      practicePrompt: 'Severe leg bleeding continues despite direct pressure. Next consideration?',
      practiceOptions: ['Tourniquet per training/protocol', 'Aspirin', 'Ignore and transport'],
      correctOptionIndex: 0,
      practiceFeedback: 'Uncontrolled severe extremity bleeding may require a tourniquet.',
    ),
    TreatmentId.woundDressing: TreatmentLesson(
      id: TreatmentId.woundDressing,
      usedFor: 'Protecting wounds and helping control bleeding.',
      whenToConsider: 'Open wounds, abrasions, lacerations, or bleeding after initial control.',
      supportingFindings: ['Open wound', 'Controlled bleeding', 'Need to cover injury', 'Burn or abrasion'],
      checkFirst: ['Bleeding controlled', 'Appropriate dressing', 'Need for pressure dressing', 'Need for occlusive dressing per training'],
      redFlags: ['Do not cover without reassessing bleeding', 'Watch for shock'],
      reassess: ['Bleeding through dressing', 'Distal PMS', 'Pain', 'Skin signs'],
      commonMistake: 'Dressing the wound but not checking if bleeding continues underneath.',
      practicePrompt: 'Bleeding is controlled with pressure. What should you do next for the open wound?',
      practiceOptions: ['Apply appropriate dressing and reassess', 'Remove all dressings repeatedly', 'Give oral glucose'],
      correctOptionIndex: 0,
      practiceFeedback: 'Cover the wound and continue reassessing bleeding and perfusion.',
    ),
    TreatmentId.splinting: TreatmentLesson(
      id: TreatmentId.splinting,
      usedFor: 'Stabilizing suspected fractures, sprains, or painful extremity injuries.',
      whenToConsider: 'Pain, deformity, swelling, or instability of an extremity.',
      supportingFindings: ['Deformity', 'Tenderness', 'Swelling', 'Limited movement', 'Pain with motion'],
      checkFirst: ['PMS before splint', 'Expose injury', 'Bleeding control', 'Immobilize joints above/below when appropriate'],
      redFlags: ['Life threats come before splinting', 'Reassess PMS after splint'],
      reassess: ['Pulse', 'Motor', 'Sensation', 'Pain', 'Skin color/temp'],
      commonMistake: 'Forgetting PMS before and after splinting.',
      practicePrompt: 'Forearm deformity with intact radial pulse. Key assessment before and after splint?',
      practiceOptions: ['PMS', 'OPQRST only', 'Blood glucose only'],
      correctOptionIndex: 0,
      practiceFeedback: 'PMS before and after splinting is critical.',
    ),
    TreatmentId.spinalMotionRestriction: TreatmentLesson(
      id: TreatmentId.spinalMotionRestriction,
      usedFor: 'Reducing movement when spinal injury is suspected per protocol.',
      whenToConsider: 'Trauma with concerning mechanism, pain, neuro deficits, altered mental status, or protocol criteria.',
      supportingFindings: ['Neck/back pain', 'Neuro complaint', 'High-risk mechanism', 'Altered LOC', 'Distracting injury'],
      checkFirst: ['Local spinal protocol', 'PMS/neuro status', 'Airway/breathing priorities', 'Need for rapid transport'],
      redFlags: ['Do not delay life-saving care', 'Airway always matters'],
      reassess: ['PMS/neuro status', 'Airway/breathing', 'Pain', 'Skin under devices'],
      commonMistake: 'Applying spinal precautions automatically without thinking through local criteria.',
      practicePrompt: 'Fall patient has neck pain and tingling in hands. What should you consider?',
      practiceOptions: ['Spinal motion restriction per protocol', 'Aspirin', 'Ignore neuro symptoms'],
      correctOptionIndex: 0,
      practiceFeedback: 'Neck pain with neuro symptoms is concerning and should trigger protocol-based spinal care.',
    ),
    TreatmentId.burns: TreatmentLesson(
      id: TreatmentId.burns,
      usedFor: 'Initial EMT care for thermal burns.',
      whenToConsider: 'Burn injury after scene safety and life threats are addressed.',
      supportingFindings: ['Thermal injury', 'Pain', 'Red/blistered/charred skin', 'Smoke exposure concern'],
      checkFirst: ['Stop burning process', 'Airway risk', 'Burn size/depth/location', 'Remove jewelry if appropriate'],
      redFlags: ['Facial burns/inhalation concern', 'Circumferential burns', 'Large burns', 'Electrical/chemical mechanisms'],
      reassess: ['Airway', 'Breathing', 'Pain', 'Shock signs', 'Burn dressing'],
      commonMistake: 'Focusing on the burn and missing airway or shock concerns.',
      practicePrompt: 'Patient has partial-thickness forearm burn, no airway concern. Initial burn care?',
      practiceOptions: ['Cool/cover per protocol and reassess', 'Apply butter', 'Ignore pain'],
      correctOptionIndex: 0,
      practiceFeedback: 'Stop the burning process, cover appropriately, and keep reassessing.',
    ),
    TreatmentId.shockManagement: TreatmentLesson(
      id: TreatmentId.shockManagement,
      usedFor: 'Supporting perfusion in suspected shock.',
      whenToConsider: 'Poor perfusion, hypotension, tachycardia, cool/pale/clammy skin, altered mental status.',
      supportingFindings: ['SBP low', 'Rapid weak pulse', 'Cool/pale/clammy', 'Delayed cap refill', 'Anxiety/confusion'],
      checkFirst: ['Control bleeding', 'Airway/breathing', 'Keep warm', 'Transport priority', 'Need ALS'],
      redFlags: ['Do not wait for BP to crash before recognizing shock', 'Treat causes you can fix'],
      reassess: ['Pulse', 'BP', 'Mental status', 'Skin signs', 'Bleeding'],
      commonMistake: 'Only calling shock when blood pressure is already very low.',
      practicePrompt: 'Patient is pale, cool, clammy with weak rapid pulse after bleeding injury. Best care bundle?',
      practiceOptions: ['Control bleeding, keep warm, rapid transport/ALS as indicated', 'Have patient walk it off', 'Give aspirin'],
      correctOptionIndex: 0,
      practiceFeedback: 'Shock care focuses on causes, warmth, reassessment, and transport priority.',
    ),
    TreatmentId.rapidTransport: TreatmentLesson(
      id: TreatmentId.rapidTransport,
      usedFor: 'Moving unstable or potentially unstable patients to definitive care quickly.',
      whenToConsider: 'Life threats, unstable vitals, severe mechanism, stroke, cardiac, major trauma, shock, or deterioration.',
      supportingFindings: ['Altered mental status', 'Respiratory distress', 'Shock signs', 'Stroke signs', 'Severe trauma', 'Persistent chest pain'],
      checkFirst: ['Critical interventions that cannot wait', 'Need ALS intercept', 'Destination per protocol', 'Ongoing reassessment'],
      redFlags: ['Do not spend unnecessary scene time on nonessential tasks'],
      reassess: ['Airway', 'Breathing', 'Circulation', 'Vitals', 'Treatment response'],
      commonMistake: 'Staying on scene too long with an unstable patient.',
      practicePrompt: 'Stroke signs started 30 minutes ago. Transport priority?',
      practiceOptions: ['Rapid transport per stroke protocol', 'Delay for full secondary exam', 'No transport needed'],
      correctOptionIndex: 0,
      practiceFeedback: 'Time-sensitive patients need early transport decisions.',
    ),
    TreatmentId.requestAls: TreatmentLesson(
      id: TreatmentId.requestAls,
      usedFor: 'Getting higher-level support when patient condition or protocol indicates.',
      whenToConsider: 'Airway/breathing/circulation threats, serious medical conditions, abnormal vitals, or medication needs outside EMT level.',
      supportingFindings: ['Respiratory failure', 'Shock', 'Serious chest pain', 'Stroke signs', 'Seizures', 'Severe allergic reaction', 'Deteriorating patient'],
      checkFirst: ['Local dispatch/ALS criteria', 'Transport time', 'Can ALS intercept or meet en route?', 'Do not delay transport unnecessarily'],
      redFlags: ['Calling ALS should not delay care or transport when patient is unstable'],
      reassess: ['Patient trend', 'Vitals', 'Interventions done', 'ETA/transport plan'],
      commonMistake: 'Requesting ALS late after the patient has already worsened.',
      practicePrompt: 'Chest pain patient is pale, sweaty, hypotensive, and worsening. What should you consider?',
      practiceOptions: ['Request ALS and rapid transport per protocol', 'Wait and see only', 'Only bandage patient'],
      correctOptionIndex: 0,
      practiceFeedback: 'Worsening unstable patients often require ALS and rapid transport decisions.',
    ),
    TreatmentId.reassessment: TreatmentLesson(
      id: TreatmentId.reassessment,
      usedFor: 'Finding patient improvement, worsening, or treatment effects.',
      whenToConsider: 'After every treatment and throughout the call.',
      supportingFindings: ['Any abnormal vital', 'Treatment given', 'Change in complaint', 'Unstable patient'],
      checkFirst: ['What was abnormal before?', 'What treatment was done?', 'How often to reassess per acuity?', 'Document changes'],
      redFlags: ['One set of vitals is not enough for a sick patient'],
      reassess: ['Primary assessment', 'Vitals', 'Pain', 'Mental status', 'Treatment effect'],
      commonMistake: 'Giving a treatment and never checking if it helped.',
      practicePrompt: 'After giving oxygen for SpO₂ 88%, what must be checked?',
      practiceOptions: ['SpO₂, breathing effort, mental status, overall condition', 'Only patient address', 'No reassessment needed'],
      correctOptionIndex: 0,
      practiceFeedback: 'Treatment decisions are incomplete without reassessment.',
    ),
    TreatmentId.oralGlucose: TreatmentLesson(
      id: TreatmentId.oralGlucose,
      usedFor: 'Suspected low blood sugar in a conscious patient who can swallow.',
      whenToConsider: 'Altered mental status with diabetic history or signs of hypoglycemia.',
      supportingFindings: ['Confusion', 'Weakness', 'Sweating', 'Diabetic history', 'Low glucose if available'],
      checkFirst: ['Patient can swallow', 'Patient can protect airway', 'Local protocol', 'Glucose reading if available'],
      redFlags: ['Do not give oral glucose to a patient who cannot protect their airway'],
      reassess: ['Mental status', 'Airway', 'Ability to swallow', 'Glucose if available'],
      commonMistake: 'Giving oral glucose to a patient who is too altered to swallow safely.',
      practicePrompt: 'Confused diabetic patient is awake, can follow commands, and can swallow. What may be considered?',
      practiceOptions: ['Oral glucose per protocol', 'Aspirin', 'Tourniquet'],
      correctOptionIndex: 0,
      practiceFeedback: 'Oral glucose may be appropriate only if the patient can swallow/protect the airway and protocol allows.',
    ),
    TreatmentId.aspirin: TreatmentLesson(
      id: TreatmentId.aspirin,
      usedFor: 'Suspected cardiac chest pain.',
      whenToConsider: 'Chest pain or pressure that could be cardiac.',
      supportingFindings: ['Chest pressure', 'Radiation to arm/jaw/back/neck', 'Shortness of breath', 'Nausea', 'Sweating', 'Cardiac history'],
      checkFirst: ['Aspirin allergy', 'Active bleeding or recent major bleeding history', 'Ability to swallow', 'Local protocol'],
      redFlags: ['Do not give just because any pain is in the chest; check contraindications'],
      reassess: ['Chest pain', 'Blood pressure', 'Mental status', 'Patient condition'],
      commonMistake: 'Giving aspirin without checking allergy or bleeding concerns.',
      practicePrompt: 'Crushing chest pressure, pale/cool skin, no aspirin allergy, can swallow. What should be considered?',
      practiceOptions: ['Aspirin per protocol', 'Oral glucose', 'Tourniquet'],
      correctOptionIndex: 0,
      practiceFeedback: 'Aspirin may be indicated for suspected cardiac chest pain after contraindication checks.',
    ),
    TreatmentId.nitroglycerinAssist: TreatmentLesson(
      id: TreatmentId.nitroglycerinAssist,
      usedFor: 'Assisting with prescribed nitroglycerin for suspected cardiac chest pain when allowed.',
      whenToConsider: 'Patient has prescribed nitro and chest pain consistent with cardiac concern.',
      supportingFindings: ['Cardiac history', 'Prescribed nitro', 'Chest pressure', 'Stable enough per protocol'],
      checkFirst: ['Patient prescription', 'Blood pressure threshold', 'Recent erectile dysfunction meds per protocol', 'Max doses/time', 'Medical direction/local protocol'],
      redFlags: ['Hypotension', 'No prescription when assist-only system', 'Contraindicated meds', 'Altered patient unable to cooperate'],
      reassess: ['Blood pressure', 'Chest pain', 'Mental status', 'Dizziness/weakness'],
      commonMistake: 'Assisting nitro without checking blood pressure or protocol contraindications.',
      practicePrompt: 'Chest pain patient has prescribed nitro but SBP is 82. Best answer?',
      practiceOptions: ['Do not assist; check protocol/medical direction', 'Assist immediately', 'Give oral glucose'],
      correctOptionIndex: 0,
      practiceFeedback: 'Low blood pressure is a major red flag for nitroglycerin assistance.',
    ),
    TreatmentId.epinephrineAutoInjector: TreatmentLesson(
      id: TreatmentId.epinephrineAutoInjector,
      usedFor: 'Severe allergic reaction/anaphylaxis when protocol allows.',
      whenToConsider: 'Allergic reaction with airway, breathing, circulation, or widespread systemic signs.',
      supportingFindings: ['Wheezing', 'Throat/tongue swelling', 'Hypotension', 'Hives plus respiratory symptoms', 'Known allergen exposure'],
      checkFirst: ['Signs of anaphylaxis', 'Auto-injector availability/expiration if assisting', 'Dose/device', 'Local protocol/medical direction'],
      redFlags: ['Do not dismiss respiratory or shock signs in allergic reactions'],
      reassess: ['Airway swelling', 'Breathing', 'BP', 'Pulse', 'Need ALS/rapid transport'],
      commonMistake: 'Treating anaphylaxis like a minor rash.',
      practicePrompt: 'Bee sting patient has hives, wheezing, throat tightness, and dizziness. What should be considered?',
      practiceOptions: ['Epinephrine auto-injector per protocol and ALS/transport', 'Aspirin', 'No care needed'],
      correctOptionIndex: 0,
      practiceFeedback: 'Airway/breathing/circulation involvement suggests anaphylaxis and urgent care.',
    ),
    TreatmentId.albuterolAssist: TreatmentLesson(
      id: TreatmentId.albuterolAssist,
      usedFor: 'Bronchospasm/wheezing when protocol allows assist or administration.',
      whenToConsider: 'Respiratory distress with wheezing and asthma/COPD history or prescribed inhaler/nebulizer.',
      supportingFindings: ['Wheezing', 'Asthma/COPD history', 'Increased work of breathing', 'Short phrases', 'Low SpO₂'],
      checkFirst: ['Patient prescription/device if assist-only', 'Contraindications per protocol', 'Can patient cooperate?', 'Need oxygen/BVM/ALS'],
      redFlags: ['Silent chest or fatigue can be worse than wheezing', 'Do not delay ventilation support'],
      reassess: ['Lung sounds', 'Work of breathing', 'SpO₂', 'Pulse', 'Mental status'],
      commonMistake: 'Giving inhaler help but not reassessing lung sounds/work of breathing.',
      practicePrompt: 'Asthma patient wheezing, has own inhaler, and is alert. What may be appropriate?',
      practiceOptions: ['Assist/administer albuterol per protocol', 'Tourniquet', 'Ignore wheezing'],
      correctOptionIndex: 0,
      practiceFeedback: 'Bronchodilator use depends on local protocol and patient/device factors.',
    ),
    TreatmentId.naloxone: TreatmentLesson(
      id: TreatmentId.naloxone,
      usedFor: 'Suspected opioid overdose with respiratory depression when protocol allows.',
      whenToConsider: 'Altered mental status with slow/inadequate breathing and opioid concern.',
      supportingFindings: ['Respiratory depression', 'Pinpoint pupils may be present', 'Drug paraphernalia/history', 'Unresponsive or very sleepy'],
      checkFirst: ['Airway and ventilation support first', 'Local protocol and route', 'Scene safety', 'Need ALS/transport'],
      redFlags: ['Naloxone does not replace ventilations', 'Prepare for vomiting/agitation'],
      reassess: ['Respiratory rate/quality', 'Mental status', 'Airway', 'Need repeat dose per protocol'],
      commonMistake: 'Waiting for naloxone instead of ventilating the patient.',
      practicePrompt: 'Unresponsive patient with RR 4/min and suspected opioid use. First priority?',
      practiceOptions: ['Support airway/ventilation; naloxone per protocol', 'Ask SAMPLE first', 'Give aspirin'],
      correctOptionIndex: 0,
      practiceFeedback: 'Ventilation is the immediate life-saving priority; naloxone may also be indicated per protocol.',
    ),
    TreatmentId.activatedCharcoal: TreatmentLesson(
      id: TreatmentId.activatedCharcoal,
      usedFor: 'Some poisonings/ingestions only when protocol or medical control directs.',
      whenToConsider: 'Specific ingestion cases where medical direction/protocol approves.',
      supportingFindings: ['Recent ingestion', 'Poison control/medical direction involvement', 'Patient can swallow/protect airway'],
      checkFirst: ['Medical direction/protocol', 'Substance type', 'Time since ingestion', 'Airway protection', 'Contraindications'],
      redFlags: ['Do not use for all poisonings', 'Airway risk', 'Caustics/hydrocarbons depending on protocol'],
      reassess: ['Airway', 'Mental status', 'Vomiting', 'Vitals'],
      commonMistake: 'Thinking activated charcoal is automatic for every overdose.',
      practicePrompt: 'Patient swallowed unknown cleaner and is vomiting. What is safest answer?',
      practiceOptions: ['Contact medical direction/poison control; do not give automatically', 'Give charcoal automatically', 'Give aspirin'],
      correctOptionIndex: 0,
      practiceFeedback: 'Activated charcoal is highly protocol/medical-control dependent and not for every ingestion.',
    ),
  };
}

class DecisionScenario {
  const DecisionScenario({required this.title, required this.findings, required this.bestChoices, required this.avoidChoices, required this.feedback});

  final String title;
  final List<String> findings;
  final List<TreatmentId> bestChoices;
  final List<TreatmentId> avoidChoices;
  final String feedback;
}

class DecisionScenarios {
  static const List<DecisionScenario> all = [
    DecisionScenario(
      title: 'Shortness of breath',
      findings: ['RR 30/min', 'SpO₂ 88% RA', 'Tripod position', 'Wheezing'],
      bestChoices: [TreatmentId.oxygen, TreatmentId.positionOfComfort, TreatmentId.albuterolAssist, TreatmentId.requestAls, TreatmentId.reassessment],
      avoidChoices: [TreatmentId.aspirin, TreatmentId.tourniquet],
      feedback: 'Support breathing, consider bronchodilator per protocol, and reassess response.',
    ),
    DecisionScenario(
      title: 'Cardiac chest pressure',
      findings: ['Chest pressure', 'Pale/cool/diaphoretic', 'No aspirin allergy', 'Can swallow'],
      bestChoices: [TreatmentId.aspirin, TreatmentId.oxygen, TreatmentId.positionOfComfort, TreatmentId.requestAls, TreatmentId.rapidTransport, TreatmentId.reassessment],
      avoidChoices: [TreatmentId.oralGlucose, TreatmentId.tourniquet],
      feedback: 'Suspected ACS care includes protocol-based aspirin consideration, ALS/transport decisions, and reassessment.',
    ),
    DecisionScenario(
      title: 'Altered diabetic patient',
      findings: ['Confused', 'Diabetic history', 'Pale and sweaty', 'Awake and can swallow'],
      bestChoices: [TreatmentId.oralGlucose, TreatmentId.oxygen, TreatmentId.reassessment, TreatmentId.requestAls],
      avoidChoices: [TreatmentId.aspirin, TreatmentId.nitroglycerinAssist],
      feedback: 'Oral glucose may be considered if the patient can swallow and local protocol allows.',
    ),
    DecisionScenario(
      title: 'Major extremity bleeding',
      findings: ['Severe leg bleeding', 'Weak rapid pulse', 'Pale/cool/clammy', 'Direct pressure not enough'],
      bestChoices: [TreatmentId.bleedingControl, TreatmentId.tourniquet, TreatmentId.shockManagement, TreatmentId.rapidTransport, TreatmentId.requestAls, TreatmentId.reassessment],
      avoidChoices: [TreatmentId.aspirin, TreatmentId.positionOfComfort],
      feedback: 'Control the hemorrhage, treat for shock, and move toward rapid transport.',
    ),
    DecisionScenario(
      title: 'Suspected opioid overdose',
      findings: ['Unresponsive', 'RR 4/min', 'Shallow breathing', 'Drug paraphernalia nearby'],
      bestChoices: [TreatmentId.airwayPositioning, TreatmentId.bvm, TreatmentId.naloxone, TreatmentId.requestAls, TreatmentId.rapidTransport, TreatmentId.reassessment],
      avoidChoices: [TreatmentId.aspirin, TreatmentId.oralGlucose],
      feedback: 'Ventilation support comes first; naloxone may be appropriate per protocol.',
    ),
  ];
}
